version: '3.7'

networks:
 default:
   external:
     name: planner

services:
  front:
    build: .
    container_name: planner-front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/vladimir/ssl/:/etc/ssl/
