name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository 
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "."
        target: ${{ secrets.PROJECT_PATH }}

    - name: Build project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          echo VUE_APP_BACKEND_DOMAIN=http://${{ secrets.HOST }}:8000/ > .env
          echo VUE_APP_DOMAIN=http://${{ secrets.HOST }}/ >> .env
          echo VUE_APP_VK_APP_ID=${{ secrets.VK_APP_ID }} >> .env
          echo VUE_APP_VK_RESPONSE_URI=http://${{ secrets.HOST }}/auth/vk/success/ >> .env
          docker-compose up --build -d
